#! /bin/sh

sxhkd &
ulauncher --hide-window --no-window-shadow &
nm-applet &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap			 7 
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a polybar border=off manage=off
bspc rule -a ulauncher focus=on
bspc rule -a vlc desktop='^9' state=fullscreen

compton &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
wmname LG3D &
